version: '3.9'

services:
  fastapi:
    container_name: chat-back
    build: ..
    command: uvicorn --factory presentation.api.app:create_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../src:/app/
    ports:
      - 8000:8000
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge