version: '3.9'

services:
  mongodb:
    image: bitnami/mongodb:6.0
    ports:
      - "27017:27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - backend
    volumes:
      - dbdata6:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabitmq-messages:/var/lib/rabbitmq/
        - rabitmq-logs:/var/log/rabbitmq
    networks:
      - backend
    env_file:
      - .env

volumes:
  dbdata6:
  rabitmq-messages:
  rabitmq-logs:

networks:
  backend:
    driver: bridge